<?php

$objets = array(
	// Génériques
	"OD" => "plate",
	"Nourriture" => "food_biscuit",
	"Bouffe" => "food_biscuit",
	"Animal" => "pet_pig",
	"Drogue" => "drug",
	"Alcool" => "vodka",
	
	// Utilitaires
	"Appareil électronique en panne" => "electro_box",
	"Appareil électronique" => "electro_box",
	"Appareil electronique" => "electro_box",
	"Appareil" => "electro_box",
	"Pile" => "pile",
	"Tournevis" => "screw",
	"Canif dérisoire" => "small_knife",
	"Canif" => "small_knife",
	"Ciment" => "concrete",
	"Sac de ciment" => "concrete",
	"Chat" => "pet_cat",
	"Gros chat mignon" => "pet_cat",
	"cadenas" => "lock",
	"Chaîne de Porte + cadenas" => "lock",
	"Chaîne" => "chain",
	"Chaine" => "chain",
	"Chaîne rouillée" => "chain",
	"Chaine rouilléé" => "chain",
	"Cochon" => "pet_pig",
	"Cochon malodorant" => "pet_pig",
	"Courroie" => "courroie",
	"Dévastator incomplet" => "big_pgun_part",
	"Dévastator" => "big_pgun_part",
	"Devastator incomplet" => "big_pgun_part",
	"Devastator" => "big_pgun_part",
	"Grosse chaîne rouilléé" => "chain",
	"Grosse chaine rouilléé" => "chain",
	"Ouvre-boîte" => "can_opener",
	"Ouvre-boite" => "can_opener",
	"Ouvre boite" => "can_opener",
	"Ouvre boîte" => "can_opener",
	"Boîte en métal" => "chest",
	"Boite en métal" => "chest",
	"Boîte" => "chest",
	"Boite" => "chest",
	"Poignée de vis et écrous" => "meca_parts",
	"Jerrycan" => "jerrycan",
	"Jeu de cartes" => "cards",
	"Jeu de cartes incomplet" => "cards",
	"Cartes" => "cards",
	"Kit de bricolage" => "repair_kit",
	"PVE" => "meca_parts",
	"Vis" => "meca_parts",
	"Poignée de vis" => "meca_parts",
	"Planche tordue" => "wood2",
	"Planche" => "wood2",
	"Ferraille" => "metal",
	"Explosif" => "explo",
	"Dynamite" => "explo",
	"Explosif brut" => "explo",
	"Pétard" => "explo",
	"Explosifs bruts" => "explo",
	"Bandage rudimentaire" => "bandage",
	"Bandage" => "bandage",
	"Boîte d'allumettes" => "lights",
	"Boite d'allumettes" => "lights",
	"Viande Humaine" => "hmeat",
	"Sac plastique" => "grenade_empty",
	"Sac" => "grenade_empty",
	"Rustine" => "rustine",
	"Poule" => "pet_chick",
	"Rat géant" => "pet_rat",
	"Rat" => "pet_rat",
	"Tube de cuivre" => "tube",
	"Tube" => "tube",
	"Produits pharmaceutiques" => "pharma",
	"PP" => "pharma",
	"Composant électronique" => "electro",
	"Composant" => "electro",
	"Compo" => "electro",
	"Moteur" => "engine",
	"Mécanisme" => "mecanism",
	"Radio K7 éteint" => "radio_off",
	"Radio" => "radio_off",
	"Radius mark II" => "radius_mk2",
	"Radius mark 2" => "radius_mk2",
	"Mark II" => "radius_mk2",
	"Pistolet à Eau" => "watergun_empty",
	"Pistolet" => "watergun_empty",
	"Lance-Pile 1-PDTG" => "pilegun_empty",
	"Lance-pile" => "pilegun_empty",
	"Vieille machine à laver" => "machine_1",
	"Vieille machine a laver" => "machine_1",
	"Machine à laver" => "machine_1",
	"Machine a laver" => "machine_1",
	"Meuble en kit" => "deco_box",
	"Meubles en kit" => "deco_box",
	"Meuble" => "deco_box",
	"Meubles" => "deco_box",
	"Nesquick" => "digger",
	"Nessquick" => "digger",
	"Ness-quick" => "digger",
	"Désherbant" => "digger",
	"Désherbant Nesquick" => "digger",
	"Désherbant Ness-Quick" => "digger",
	"Balise Radius" => "tagger",
	"Balise" => "tagger",
	"Détonateur compact" => "deto",
	"Détonateur" => "deto",
	"Paracétoïde 7g" => "disinfect",
	"Paracétoïde" => "disinfect",
	"Paracet" => "disinfect",
	"Os charnu" => "bone_meat",
	"Os" => "bone_meat",
	"Poutre rafistolée" => "wood_beam",
	"Poutre" => "wood_beam",
	"PMV" => "vibr_empty",
	"Petit manche vibrant" => "vibr_empty",
	"Serpent" => "pet_snake",
	"Serpent de 2 mètres" => "pet_snake",
	"Four" => "machine_2",
	"Four cancérigène" => "machine_2",
	"Sport-elec" => "sport_elec_empty",
	"Sport-élec" => "sport_elec_empty",
	"Sportelec" => "sport_elec_empty",
	"Structures métalliques" => "metal_beam",
	"Structure" => "metal_beam",
	"Souche de bois pourrie" => "wood_bad",
	"Souche de bois" => "wood_bad",
	"Souche" => "wood_bad",
	"Twinoïde" => "drug_hero",
	"Twinoide" => "drug_hero",
	"Twin" => "drug_hero",
	"Twinoïde 500mg" => "drug_hero",
	"Twinoide 500mg" => "drug_hero",
	"Vodka" => "vodka",
	"Vodka Marinostov" => "vodka",
	"Brico'Facile" => "repair_one",
	"Brico" => "repair_one" // end
	);

// Prévoir d'autres orhtographes
foreach($objets as $objet => $img)
{
	$objets[strtolower($objet)] = $img; // sans majuscule
	$objets[strtolower($objet)."s"] = $img; // au pluriel
}

function listobjets()
{
	global $objets;
	
	$out = "<table>";
	$out .= "<tr><td colspan=\"2\">Butin</td></tr>";
	foreach($objets as $objet => $image)
		$out .= "";
	$out .= "</table>";
}


?>